name: Test
on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker And Run Container With SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USER }}
          key: ${{ secrets.TEST_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dingtalk-vue/
            git pull origin test
            npm install
            npm run build:stage
            docker build -t dingtalk_vue .
            docker container stop dingtalk_vue
            docker container rm dingtalk_vue
            docker run -d --net dingtalk-net -p 8089:80 -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime --name dingtalk_vue  dingtalk_vue
            docker image prune -f
